# Generated by Django 4.0.4 on 2023-01-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='buttons',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
