# Generated by Django 4.0.4 on 2023-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0002_group1_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
