# Generated by Django 4.0.4 on 2023-01-23 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0003_group1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='image',
        ),
        migrations.AddField(
            model_name='group1',
            name='news_img',
            field=models.FileField(default=1, upload_to='pictures/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
            preserve_default=False,
        ),
    ]
