# Generated by Django 4.0.4 on 2023-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0004_remove_group1_image_group1_news_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='news_img',
        ),
        migrations.AddField(
            model_name='group1',
            name='svg_file',
            field=models.FileField(default=1, upload_to='svgs/'),
            preserve_default=False,
        ),
    ]
