# Generated by Django 4.1.3 on 2023-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0005_remove_group1_news_img_group1_svg_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group2',
            old_name='name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='group2',
            name='description',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group2',
            name='icons',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
