# Generated by Django 4.1.3 on 2023-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0006_rename_name_group2_topic_group2_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group2',
            name='icons',
            field=models.CharField(max_length=100),
        ),
    ]
