# Generated by Django 4.1.3 on 2023-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0007_alter_group2_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group2',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
