# Generated by Django 4.1.3 on 2023-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0010_remove_group3_image_remove_group6_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group6',
            old_name='svg_file',
            new_name='svg_file1',
        ),
        migrations.AddField(
            model_name='group6',
            name='svg_file2',
            field=models.FileField(default=1, upload_to='svgs/'),
            preserve_default=False,
        ),
    ]
