# Generated by Django 4.1.3 on 2023-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0011_rename_svg_file_group6_svg_file1_group6_svg_file2'),
    ]

    operations = [
        migrations.CreateModel(
            name='group7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=200)),
                ('SubHeading1', models.CharField(max_length=200)),
                ('description1', models.TextField(max_length=400)),
                ('SubHeading2', models.CharField(max_length=200)),
                ('description2', models.TextField(max_length=400)),
                ('SubHeading3', models.CharField(max_length=200)),
                ('description3', models.TextField(max_length=400)),
            ],
        ),
    ]
