# Generated by Django 4.1.3 on 2023-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0012_group7'),
    ]

    operations = [
        migrations.CreateModel(
            name='group8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('customer', models.IntegerField()),
                ('offers', models.CharField(max_length=200)),
            ],
        ),
    ]
