# Generated by Django 4.1.3 on 2023-01-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0013_group8'),
    ]

    operations = [
        migrations.CreateModel(
            name='group81',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='group8',
            name='offers',
        ),
        migrations.AlterField(
            model_name='group8',
            name='customer',
            field=models.CharField(max_length=200),
        ),
    ]
