# Generated by Django 4.1.3 on 2023-01-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0014_group81_remove_group8_offers_alter_group8_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group8',
            new_name='group80',
        ),
    ]
