# Generated by Django 4.1.3 on 2023-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0015_rename_group8_group80'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group80',
            name='customer',
            field=models.IntegerField(max_length=200),
        ),
    ]
