# Generated by Django 4.1.3 on 2023-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0016_alter_group80_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group80',
            name='customer',
            field=models.BigIntegerField(max_length=200),
        ),
    ]
