# Generated by Django 4.1.3 on 2023-01-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0018_group9'),
    ]

    operations = [
        migrations.AddField(
            model_name='group9',
            name='svg_file',
            field=models.FileField(default=1, upload_to='svg/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group80',
            name='customer',
            field=models.BigIntegerField(),
        ),
    ]
