# Generated by Django 4.1.3 on 2023-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0020_remove_group9_svg_file_group9_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group9',
            name='quote',
            field=models.TextField(max_length=500),
        ),
    ]
