# Generated by Django 4.0.4 on 2023-01-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0022_group100_group101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group100',
            new_name='groups100',
        ),
        migrations.RenameModel(
            old_name='group101',
            new_name='groups101',
        ),
    ]
