# Generated by Django 4.1.3 on 2023-01-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0023_rename_group100_groups100_rename_group101_groups101'),
    ]

    operations = [
        migrations.CreateModel(
            name='about1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('paragraph', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='about2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='about3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data_value', models.CharField(blank=True, max_length=200, null=True)),
                ('data_suffix', models.CharField(blank=True, default='+', max_length=200, null=True)),
            ],
        ),
    ]
