# Generated by Django 4.1.3 on 2023-01-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0024_about1_about2_about3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about3',
            name='data_suffix',
            field=models.CharField(blank=True, default='+', max_length=200),
        ),
    ]
