# Generated by Django 4.1.3 on 2023-01-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0025_alter_about3_data_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='about4_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
            ],
        ),
    ]
