# Generated by Django 4.1.3 on 2023-01-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0026_about4_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='about4_video',
            name='title',
            field=models.CharField(default='YouTube video player', max_length=200),
        ),
    ]
