# Generated by Django 4.1.3 on 2023-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0028_about6'),
    ]

    operations = [
        migrations.CreateModel(
            name='service2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=200)),
                ('type1', models.CharField(max_length=200)),
                ('type2', models.CharField(max_length=200)),
                ('type3', models.CharField(max_length=200)),
                ('type4', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icons', models.CharField(max_length=100)),
                ('buttons', models.CharField(max_length=200)),
            ],
        ),
    ]
