# Generated by Django 4.0.4 on 2023-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0030_contact1_contact2_contact3'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='contact1',
            old_name='icons',
            new_name='des',
        ),
        migrations.AddField(
            model_name='contact1',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
