# Generated by Django 4.0.4 on 2023-01-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0031_contact4_rename_icons_contact1_des_contact1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact3',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
