# Generated by Django 4.0.4 on 2023-01-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0032_alter_contact3_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact1',
            name='svg_file',
            field=models.FileField(default=1, upload_to='svg/'),
            preserve_default=False,
        ),
    ]
