# Generated by Django 4.0.4 on 2023-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0033_contact1_svg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prices2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
                ('service1', models.CharField(blank=True, max_length=200)),
                ('service2', models.CharField(blank=True, max_length=200)),
                ('service3', models.CharField(blank=True, max_length=200)),
                ('service4', models.CharField(blank=True, max_length=200)),
                ('service5', models.CharField(blank=True, max_length=200)),
                ('buttons', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prices3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prices4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.CharField(blank=True, max_length=200)),
                ('topic_des', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prices5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
                ('buttons', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prices6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('plan_bill', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
