# Generated by Django 4.0.4 on 2023-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0037_prices5_sec_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices4',
            name='data_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
