# Generated by Django 4.0.4 on 2023-01-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0038_prices4_data_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='group2',
            name='delay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
