# Generated by Django 4.1.6 on 2023-02-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0041_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='name',
            new_name='dname',
        ),
    ]
