# Generated by Django 4.1.6 on 2023-02-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0042_rename_name_demo_dname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='confirm_password',
            new_name='demo_confirm_password',
        ),
        migrations.RenameField(
            model_name='demo',
            old_name='email',
            new_name='demo_email',
        ),
        migrations.RenameField(
            model_name='demo',
            old_name='dname',
            new_name='demo_name',
        ),
        migrations.RenameField(
            model_name='demo',
            old_name='password',
            new_name='demo_password',
        ),
    ]
