# Generated by Django 4.1.6 on 2023-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0043_rename_confirm_password_demo_demo_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=200)),
                ('icon_links', models.CharField(max_length=400)),
            ],
        ),
    ]
