# Generated by Django 4.1.6 on 2023-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesite', '0044_footermedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='demo_confirm_password',
            new_name='demo_pnumber',
        ),
        migrations.RenameField(
            model_name='demo',
            old_name='demo_password',
            new_name='demo_subject',
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_img',
            field=models.FileField(upload_to='svgs/'),
        ),
    ]
